# SPOTIFY DATASET

### Imagine you are working with a music group or artist to help them make more money on Spotify. 
- Artists on spotify make money based on streams. 
- Investigate the data to help your client get as many streams as possible.
- What can an artist do to get more streams?
- What song charactaristics are related to the number of streams?

## DOWNLOAD THE DATA

In [1]:
# Import libraries
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

In [2]:
# Go to https://www.kaggle.com/datasets/nelgiriyewithana/top-spotify-songs-2023/data and download the dataset

In [3]:
# Open the csv in the notebook. Name it df. You might have to change the encoding
df = pd.read_csv("C:\\Users\\nyolc\\OneDrive\\Asztali g√©p\\CS251\\spotify-2023.csv", encoding = "ISO-8859-1")

In [4]:
# to show all columns:
pd.set_option('display.max_columns', None);

## EXPLORING THE DATA

In [5]:
# View the first 3 rows
df.head()
df.shape

(953, 24)

In [6]:
# View the last 3 rows
df.tail(3)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,0,7,0,0,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,26,17,0,0,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,18,32,1,0,90,E,Minor,61,32,67,15,0,11,5

In [7]:
# view a random sample from the dataset
df.sample(5)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
10,un x100to,"Bad Bunny, Grupo Frontera",2,2023,4,17,2876,40,505671438,41,205,54,12,251,83,F#,Minor,57,56,72,23,0,27,5
810,TUS L√Ø¬ø¬Ω√Ø¬ø¬ΩGR,"Sech, Mora",2,2022,4,1,1308,2,184622518,23,16,9,0,5,174,C#,Major,68,45,71,18,0,11,25
783,Worldwide Steppers,Kendrick Lamar,1,2022,5,13,1480,0,61739839,1,0,5,0,0,72,A#,Minor,56,56,47,76,0,8,36
697,Something In The Way - Remastered 2021,Nirvana,1,1991,9,24,9514,0,368646862,45,27,"1,197",0,43,106,G#,Major,44,8,20,74,42,11,3
646,Mi√Ø¬ø¬Ω√Ø¬ø¬Ωn,"Tini, Maria Becerra",2,2021,4,29,3406,16,596152090,61,23,70,1,0,92,D,Major,85,92,54,16,0,29,7

In [8]:
# view the shape (rows and columns)
df.shape

(953, 24)

In [9]:
# Check if any columns have null values

In [10]:
#what is the track name of the third row of the database?
df.iloc[2,0]

'vampire'

In [11]:
#what is the released year of the third to last row of the database?
df.iloc[-3,3]

2022

In [12]:
#tow collumns have null values. Which one has more?
df.isnull().sum()

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

In [13]:
#Are there any duplicate rows in the dataset?
df.duplicated().sum()

0

In [14]:
#Wgat is dtype of streams?
df["streams"].dtype

dtype('O')

In [15]:
#

In [16]:
#what is the minimum released year?
df["released_year"].min()

1930

In [17]:
#total null values in the dataset
df.isnull().sum().sum()

145

In [18]:
# check for duplicated values:
df.duplicated().sum()

0

In [19]:
# View the columns
df.columns

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm',
       'key', 'mode', 'danceability_%', 'valence_%', 'energy_%',
       'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%'],
      dtype='object')

In [20]:
# We are only going to look at columns related to spotify 
# either drop the unrelated columns or select only the columns you want to keep
df = df.drop(columns=['in_apple_playlists', 'in_apple_charts', 'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts'])

In [21]:
# These columns should be removed: 
# 'in_apple_playlists', 'in_apple_charts','in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts'

In [22]:
# You should be left with these columns:
df
# ['track_name', 'artist(s)_name', 'artist_count', 'released_year', 'released_month', 'released_day', 
# 'in_spotify_playlists','in_spotify_charts', 'streams', 'bpm','key', 'mode', 'danceability_%', 'valence_%', 
# 'energy_%','acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%']

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,90,E,Minor,61,32,67,15,0,11,5

In [23]:
# Check out the info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   bpm                   953 non-null    int64
 10  key                   858 non-null    object
 11  mode                  953 non-null    object
 12  danceability_%        953 non-null    int64
 13  valence_%             953 non-null    int64
 14  energy_%              953 non-null    int64
 15  acousticness_%        953 non-null    int64
 16  instrumentalness_%    953 non-null    int64
 17  liveness_%            953 non-null    int64
 18  speechiness_%         953 non-null    int64
dtypes: int64(14), object(5)
memory usage: 141.6+ KB

In [24]:
# describe the dataframe

round(df.describe())

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.0,953.0,953.0,953.0,953.0,953.0,953.0,953.0,953.0,953.0,953.0,953.0,953.0,953.0
mean,2.0,2018.0,6.0,14.0,5200.0,12.0,123.0,67.0,51.0,64.0,27.0,2.0,18.0,10.0
std,1.0,11.0,4.0,9.0,7898.0,20.0,28.0,15.0,23.0,17.0,26.0,8.0,14.0,10.0
min,1.0,1930.0,1.0,1.0,31.0,0.0,65.0,23.0,4.0,9.0,0.0,0.0,3.0,2.0
25%,1.0,2020.0,3.0,6.0,875.0,0.0,100.0,57.0,32.0,53.0,6.0,0.0,10.0,4.0
50%,1.0,2022.0,6.0,13.0,2224.0,3.0,121.0,69.0,51.0,66.0,18.0,0.0,12.0,6.0
75%,2.0,2022.0,9.0,22.0,5542.0,16.0,140.0,78.0,70.0,77.0,43.0,0.0,24.0,11.0
max,8.0,2023.0,12.0,31.0,52898.0,147.0,206.0,96.0,97.0,97.0,97.0,91.0,97.0,64.0

### Looking at the above table:
1. what is the max value of artist_count?
2. what is median (50%) value for amount of times in spotify playlists?

In [25]:
# 1. Max value of artist count: 
df["artist_count"].max()

# 2. Median value for amount of times on spotify playlists: 
df["in_spotify_playlists"].median()

2224.0

In [26]:
# Use iloc to focus on rows 200 - 205 and columns 3-7
df.iloc[200:206, 3:8]

,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts
200,2023,6,2,551,4
201,2023,5,1,577,14
202,2023,5,11,955,29
203,2022,11,24,995,19
204,2023,5,15,178,6
205,2023,6,2,290,19

In [27]:

# Use .loc to focus on rows 870-874 and columns ['artist(s)_name' and 'danceability_%']
df.loc[870:874, ['artist(s)_name', 'danceability_%']]

    artist(s)_name  danceability_%
870         j-hope              78
871  Guns N' Roses              45
872      Burna Boy              80
873      Rosa Linn              56
874          Drake              88

In [28]:
# use [] to look at rows 20 and 21. 
df[20:22]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
20,LADY GAGA,"Gabito Ballesteros, Junior H, Peso Pluma",3,2023,6,22,332,26,86444842,140,F,Minor,65,87,74,22,0,42,4
21,I Can See You (Taylor√Ø¬ø¬Ω√Ø¬ø¬Ω√Ø¬ø¬Ωs Version) (From...,Taylor Swift,1,2023,7,7,516,38,52135248,123,F#,Major,69,82,76,6,0,6,3

In [29]:
# Find rows with nulls
df[df.isnull().any(axis=1)]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
12,Flowers,Miley Cyrus,1,2023,1,12,12211,115,1316855716,118,NaN,Major,71,65,68,6,0,3,7
17,What Was I Made For? [From The Motion Picture ...,Billie Eilish,1,2023,7,13,873,104,30546883,78,NaN,Major,44,14,9,96,0,10,3
22,I Wanna Be Yours,Arctic Monkeys,1,2013,1,1,12859,110,1297026226,135,NaN,Minor,48,44,42,12,2,11,3
35,Los del Espacio,"Big One, Duki, Lit Killah, Maria Becerra, FMK,...",8,2023,6,1,1150,31,123122413,120,NaN,Major,81,63,68,11,0,11,4
44,Barbie World (with Aqua) [From Barbie The Album],"Nicki Minaj, Aqua, Ice Spice",3,2023,6,23,1117,80,65156199,144,NaN,Major,77,75,58,52,0,23,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899,Hold Me Closer,"Elton John, Britney Spears",2,2017,11,10,4967,0,284216603,126,NaN,Major,67,49,77,11,0,19,11
901,After LIKE,IVE,1,2022,8,22,767,12,265548837,125,NaN,Major,68,80,92,10,0,9,12
903,B.O.T.A. (Baddest Of Them All) - Edit,"Interplanetary Criminal, Eliza Rose",2,2022,6,15,5153,6,244585109,137,NaN,Major,74,71,89,24,61,15,5
938,Labyrinth,Taylor Swift,1,2022,10,21,1597,0,187339835,110,NaN,Major,48,15,31,80,22,12,4
940,Sweet Nothing,Taylor Swift,1,2022,10,21,1747,0,186104310,177,NaN,Major,34,39,16,97,0,12,5

In [30]:
df.shape

(953, 19)

In [31]:
# Look at the unique values in this null row
# Are the values numbers or categories?
df["released_month"].unique()

array([ 7,  3,  6,  8,  5,  4,  1, 12,  2, 10, 11,  9], dtype=int64)

In [32]:
# We could fill the nulls with the most repeated value, or with a filler value such as 'NA' or 'Unknown'
# Let's fill the nulls with 'Unknown'
df = df.fillna('Unknown')
df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,90,E,Minor,61,32,67,15,0,11,5

In [33]:
# check that all the nulls have been replaced. The sum of all nulls in the df should be 0
df.isnull().sum().sum()

0

In [34]:
#uniwue values in the key column
df["key"].unique()

array(['B', 'C#', 'F', 'A', 'D', 'F#', 'Unknown', 'G#', 'G', 'E', 'A#',
       'D#'], dtype=object)

## REMOVE ROWS

In [35]:
# One of the columns contains a string that shouldn't be there. the rest of the values in the column are integers. 
# The column type is string due to the one string value. 
# Find the string and disply the entire row which contains the string
# remove the row. 
# reset the index and convert the column to numeric. 
import pandas as pd
df["streams"].unique()
df[~df['streams'].apply(lambda x: str(x).isdigit())]

df = df.drop(574)

In [36]:
df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,90,E,Minor,61,32,67,15,0,11,5

In [37]:
# check the dtypes
df.dtypes

track_name              object
artist(s)_name          object
artist_count             int64
released_year            int64
released_month           int64
released_day             int64
in_spotify_playlists     int64
in_spotify_charts        int64
streams                 object
bpm                      int64
key                     object
mode                    object
danceability_%           int64
valence_%                int64
energy_%                 int64
acousticness_%           int64
instrumentalness_%       int64
liveness_%               int64
speechiness_%            int64
dtype: object

In [38]:
df.shape

(952, 19)

In [39]:
#reset the index
df = df.reset_index(drop=True)
df.shape

(952, 19)

In [40]:
df.tail()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
947,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,144,A,Major,60,24,39,57,0,8,3
948,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,166,F#,Major,42,7,24,83,1,12,6
949,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,92,C#,Major,80,81,67,4,0,8,6
950,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,97,C#,Major,82,67,77,8,0,12,5
951,Alone,Burna Boy,1,2022,11,4,782,2,96007391,90,E,Minor,61,32,67,15,0,11,5

In [41]:
# There is one value that has dtype of string, although it should be an int.
# which column is it? 
# Can you print the first ten rows of that column?
df.streams.values[:10]

array(['141381703', '133716286', '140003974', '800840817', '303236322',
       '183706234', '725980112', '58149378', '95217315', '553634067'],
      dtype=object)

In [42]:
# It looks like the values are all integers, saved as strings
# But, what happens if you try to convert the column type to integer
df.streams=pd.to_numeric(df.streams)
df.streams.dtype

# Try below and see what happens

dtype('int64')

In [43]:
# One of the valuues in the column is a string. Can we find what row it is in and print the whole row?
# There are a few different ways to do this. See if you can figure one out
df[~df['streams'].apply(lambda x: str(x).isdigit())]

Empty DataFrame
Columns: [track_name, artist(s)_name, artist_count, released_year, released_month, released_day, in_spotify_playlists, in_spotify_charts, streams, bpm, key, mode, danceability_%, valence_%, energy_%, acousticness_%, instrumentalness_%, liveness_%, speechiness_%]
Index: []

In [44]:
# find the row with the value in the dataframe
df[df['streams'] == 'Unknown']

Empty DataFrame
Columns: [track_name, artist(s)_name, artist_count, released_year, released_month, released_day, in_spotify_playlists, in_spotify_charts, streams, bpm, key, mode, danceability_%, valence_%, energy_%, acousticness_%, instrumentalness_%, liveness_%, speechiness_%]
Index: []

In [45]:
#Which released_date is repated 9 times in the dataframe from released_year and released_month and released_day?    
released_date=df.groupby(['released_year', 'released_month', 'released_day']).size().sort_values(ascending=False)

In [46]:
released_date[released_date==9]

released_year  released_month  released_day
2023           3               3               9
dtype: int64

In [47]:
#What percent of songs were released on Wednesday round the nearest whole number from released_date?
released_date=df.groupby(['released_year', 'released_month', 'released_day']).size().sort_values(ascending=False)
released_date[released_date==9]/df.shape[0]*100
released_day=df.groupby(['released_day']).size().sort_values(ascending=False)
released_day[4]/df.shape[0]*100

4.0966386554621845

In [48]:
#For monday, what is the value of the meadian of streams?
monday=df[df['released_day']==0]
monday['streams'].median()

nan

In [49]:
#which artist appears 26 times as a main artist split the main artist?
df['artist(s)_name']=df['artist(s)_name'].str.split(',')
df['artist(s)_name']=df['artist(s)_name'].str[0]
df['artist(s)_name'].value_counts()
df['artist(s)_name'].value_counts()

Taylor Swift      36
The Weeknd        34
Bad Bunny         26
SZA               23
Kendrick Lamar    23
                  ..
MC Xenon           1
Treyce             1
Leo Santana        1
Kaifi Khalil       1
Selena Gomez       1
Name: artist(s)_name, Length: 458, dtype: int64

In [50]:
#WHat artist or group appears 6 times as a supporting artist not the main ?
#separate the supporting artists
df['supporting']=df['artist(s)_name'].str.split(',')
list=df['supporting'].value_counts()
list[list==6]

[Bruno Mars]       6
[Dua Lipa]         6
[Post Malone]      6
[Nicki Minaj]      6
[Justin Bieber]    6
[Fuerza Regida]    6
[Kanye West]       6
[Billie Eilish]    6
[NewJeans]         6
[Quevedo]          6
Name: supporting, dtype: int64

In [51]:
df.shape

(952, 20)

In [52]:
df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,supporting
0,Seven (feat. Latto) (Explicit Ver.),Latto,2,2023,7,14,553,147,141381703,125,B,Major,80,89,83,31,0,8,4,[Latto]
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,92,C#,Major,71,61,74,7,0,10,4,[Myke Towers]
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,138,F,Major,51,32,53,17,0,31,6,[Olivia Rodrigo]
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,170,A,Major,55,58,72,11,0,11,15,[Taylor Swift]
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,144,A,Minor,65,23,80,14,63,11,6,[Bad Bunny]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,144,A,Major,60,24,39,57,0,8,3,[Selena Gomez]
948,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,166,F#,Major,42,7,24,83,1,12,6,[Taylor Swift]
949,A Veces (feat. Feid),Feid,2,2022,11,3,573,0,73513683,92,C#,Major,80,81,67,4,0,8,6,[Feid]
950,En La De Ella,Feid,3,2022,10,20,1320,0,133895612,97,C#,Major,82,67,77,8,0,12,5,[Feid]
951,Alone,Burna Boy,1,2022,11,4,782,2,96007391,90,E,Minor,61,32,67,15,0,11,5,[Burna Boy]

In [53]:
#Which main artist has the highest average bpm?
df.groupby('artist(s)_name')['bpm'].mean().sort_values(ascending=False)

artist(s)_name
Adassa             206.0
Stephen Sanchez    202.0
Andy Williams      202.0
NMIXX              200.0
Libianca           198.0
                   ...
Kodak Black         73.5
Duncan Laurence     72.0
Tulus               72.0
Queen               71.0
Residente           71.0
Name: bpm, Length: 458, dtype: float64

In [54]:
# Since the value does not include the number of streams, and the number of streams is what we want to analize, 
# lets remove the row
df = df.drop(574)

In [55]:
# convert to numeric column
df.streams = pd.to_numeric(df.streams)

In [56]:
# check that the vaues are integers
df.streams.dtype

dtype('int64')

## DATE COLUMN

In [57]:
# import date from correct library
from datetime import date

In [58]:
# Use apply and lambda functions to combine the date columns (year, month, and day) 
# and insert it in column 6 as a new column called released_date.
df['released_date'] = df.apply(lambda x: date(int(x['released_year']), int(x['released_month']), int(x['released_day'])), axis=1)

In [59]:
# Check a sample to make sure it all worked
df.sample(5)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,supporting,released_date
410,INDUSTRY BABY (feat. Jack Harlow),Jack Harlow,2,2021,7,23,13315,0,1814349763,150,D#,Minor,74,89,70,2,0,5,6,[Jack Harlow],2021-07-23
253,Glimpse of Us,Joji,1,2022,6,10,6330,6,988515741,170,G#,Major,44,27,32,89,0,14,5,[Joji],2022-06-10
719,Wake Me Up - Radio Edit,Avicii,1,2013,1,1,50887,34,1970673297,124,D,Major,53,66,78,0,0,16,5,[Avicii],2013-01-01
220,Las Morras,BLESSD,2,2023,4,4,291,8,127026613,133,A,Minor,78,90,84,31,0,7,4,[BLESSD],2023-04-04
441,All I Want for Christmas Is You,Mariah Carey,1,1994,10,28,25653,0,1449779435,150,G,Major,34,33,63,16,0,7,4,[Mariah Carey],1994-10-28

## SPLIT STRINGS AND COLUMNS

In [60]:
# Let's split the artists into two group: 'main_artist' and 'supporting_artists'
# Insert them in columns 2 and 3 of the df
df['main_artist'] = df['artist(s)_name'].str.split(',').str[0]
df['supporting_artists'] = df['artist(s)_name'].str.split(',').str[1]

In [61]:
# drop 'artist(s)_name'
df = df.drop(columns=['artist(s)_name'])

In [62]:
# Check a sample to make sure it all worked
df.sample(5)

,track_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,supporting,released_date,main_artist,supporting_artists
848,Only Love Can Hurt Like This,1,2014,1,1,5148,0,588955257,91,G#,Major,57,30,89,10,0,33,8,[Paloma Faith],2014-01-01,Paloma Faith,NaN
245,Rich Flex,2,2022,11,4,4657,18,573633020,153,B,Minor,56,42,52,5,0,36,24,[Drake],2022-11-04,Drake,NaN
666,"Cay√Ø¬ø¬Ω√Ø¬ø¬Ω La Noche (feat. Cruz Cafun√Ø¬ø¬Ω√Ø¬ø¬Ω, Ab...",7,2022,1,14,1034,1,245400167,174,F,Minor,67,74,75,44,0,7,30,[Quevedo],2022-01-14,Quevedo,NaN
636,Permission to Dance,1,2021,7,9,1801,2,608334048,125,A,Major,70,65,74,1,0,34,4,[BTS],2021-07-09,BTS,NaN
943,The Astronaut,1,2022,10,28,481,9,203436468,125,F,Major,54,22,76,0,0,14,3,[Jin],2022-10-28,Jin,NaN

In [63]:
# print a sorted list of all the unique main artists
df['main_artist'].unique()

array(['Latto', 'Myke Towers', 'Olivia Rodrigo', 'Taylor Swift',
       'Bad Bunny', 'Dave', 'Eslabon Armado', 'Quevedo', 'Gunna',
       'Peso Pluma', 'NewJeans', 'Miley Cyrus', 'David Kushner',
       'Harry Styles', 'SZA', 'Fifty Fifty', 'Billie Eilish', 'Feid',
       'Jimin', 'Gabito Ballesteros', 'Arctic Monkeys', 'Bizarrap',
       'The Weeknd', 'Fuerza Regida', 'R√Ø¬ø¬Ω√Ø¬ø¬Ωma', 'Tainy',
       'Morgan Wallen', 'Dua Lipa', 'Troye Sivan', 'Karol G', 'Big One',
       'Yahritza Y Su Esencia', 'Junior H', 'Post Malone', 'Bebe Rexha',
       'Tyler', 'Nicki Minaj', 'OneRepublic', 'Ariana Grande',
       'David Guetta', 'Peggy Gou', 'Tom Odell', 'Kali Uchis',
       'Manuel Turizo', 'dennis', 'PinkPantheress', 'Charlie Puth',
       'Rauw Alejandro', 'Ozuna', 'Chris Molitor', 'Libianca',
       'Glass Animals', 'JVKE', 'The Neighbourhood', 'Coldplay', 'd4vd',
       'Sam Smith', 'Yandel', 'Maria Becerra', 'Vance Joy', 'Em Beihold',
       'Mc Livinho', 'Justin Bieber', 'Marshmello', 'Lewis Capaldi',
       'Chencho Corleone', 'Jain', 'Ayparia', 'Luke Combs', 'Doechii',
       'Jung Kook', 'J. Cole', 'Lana Del Rey', 'BTS', 'Future', 'Eminem',
       'Carin Leon', 'Ruth B.', 'Imagine Dragons', 'Adele',
       'Kendrick Lamar', 'Anggi Marito', 'Jasiel Nu√Ø¬ø¬Ω√Ø¬ø¬Ωez',
       'Tears For Fears', 'Loreen', 'Taiu', 'Sebastian Yatra',
       'Calvin Harris', 'Sabrina Carpenter', 'Ray Dalton', '(G)I-DLE',
       'Shakira', 'Swae Lee', 'Travis Scott', 'Sachin-Jigar',
       'Ed Sheeran', 'Veigh', 'Mc Pedrinho', 'Sog', 'Bomba Est√Ø¬ø¬Ω√Ø¬ø¬Ωreo',
       'Keane', 'New West', 'Chino Pacas', 'Natanael Cano', 'Don Omar',
       'Ana Castela', 'Bruno Mars', 'Drake', 'Chris Brown',
       'Daddy Yankee', 'Miguel', 'The Police', 'Lord Huron', 'Rihanna',
       'Alec Benjamin', 'A$AP Rocky', 'YOASOBI', 'Rosa Linn',
       'One Direction', 'Oscar Maydon', 'Radiohead', 'James Arthur',
       'Cigarettes After Sex', 'Shubh', 'Frank Ocean', 'Hozier',
       'Hotel Ugly', 'Creedence Clearwater Revival', 'Plan B', 'a-ha',
       'Kodak Black', 'Arijit Singh', 'Stray Kids', 'Becky G',
       'Metro Boomin', 'Kaliii', 'Abhijay Sharma', 'Semicenk', 'JISOO',
       'RAYE', 'Arcangel', 'BLESSD', 'Coi Leray', 'ENHYPEN', 'Lil Durk',
       'James Blake', 'Israel & Rodolffo', 'Steve Lacy', 'Beyonc√Ø¬ø',
       'Halsey', 'Nicky Jam', 'Sean Paul', 'WizKid', 'Simone Mendes',
       'Tini', 'Lil Uzi Vert', 'Sia', 'Stephen Sanchez', 'MC Caverinha',
       'Offset', 'Z√Ø¬ø¬Ω√Ø¬ø¬Ω Neto & Crist', 'Migrantes', 'Tory Lanez',
       'Joji', 'Mambo Kingz', 'Nile Rodgers', 'Agust D', 'Rich The Kid',
       'Labrinth', 'Lizzy McAlpine', 'IVE', 'sped up 8282',
       'Cartel De Santa', 'SEVENTEEN', 'NLE Choppa',
       'Grupo Marca Registrada', 'TAEYANG', 'Raim Laode', 'ROSAL√Ø¬ø¬Ω',
       'Meghan Trainor', 'sped up nightcore', 'Grupo Frontera', 'TV Girl',
       'INTERWORLD', 'El Chachito', 'RM', 'BLACKPINK', 'Nengo Flow',
       'Nicky Youre', 'IU', 'Ti√Ø¬ø¬Ω√Ø¬ø¬Ωsto', 'NF', 'Yng Lvcas', 'Kanii',
       'Mar√Ø¬ø¬Ω√Ø¬ø¬Ωlia Mendo', 'Zach Bryan', 'Melanie Martinez',
       'Mae Stephens', 'Kenia OS', 'Kordhell', 'Coolio', 'The Walters',
       'Mac DeMarco', 'Jack Black', 'Duki', 'Brray', 'Linkin Park',
       'Gorillaz', 'j-hope', 'Robin Schulz', 'Don Toliver', 'Niall Horan',
       'Central Cee', 'Mahalini', 'ThxSoMch', 'Kaifi Khalil', 'Lady Gaga',
       'Leo Santana', 'Treyce', 'MC Xenon', 'XXXTENTACION', 'J Balvin',
       'Yuridia', 'The Kid Laroi', 'Lizzo', 'Fujii Kaze',
       'Wisin & Yandel', 'King', 'P!nk', 'LE SSERAFIM', 'Lil Nas X',
       'Beach Weather', 'Baby Tate', 'R√Ø¬ø¬Ω√Ø', 'Beach House', 'Steve Aoki',
       'Conan Gray', 'Vishal-Shekhar', 'TOMORROW X TOGETHER', 'Mr.Kitty',
       'Gustavo Mioto', 'Jack Harlow', 'Elley Duh√Ø¬ø', 'Seafret',
       'Baby Rasta', 'DJ Escobar', 'Dean Lewis', 'Bellakath', 'Skrillex',
       'Kate Bush', 'Aerosmith', 'Freddie Dredd', 'Lost Frequencies',
       'Twisted', 'Kenshi Yonezu', 'Omar Apollo', 'Doja Cat',
       'James Hype', 'Pritam', 'Styrx', 'Maroon 5', 'Mariah Carey',
       'Wham!', 'Brenda Lee', 'Bobby Helms', 'Michael Bubl√Ø¬ø',
       'Andy Williams', 'Dean Martin', 'Kelly Clarkson',
       'Jos√Ø¬ø¬Ω√Ø¬ø¬Ω Felic', 'The Ronettes', 'John Lennon', 'Burl Ives',
       'Nat King Cole', 'Paul McCartney', 'Band Aid', "Shakin' Stevens",
       'Frank Sinatra', 'Bing Crosby', 'Chris Rea', 'Darlene Love',
       'Perry Como', 'Britney Spears', 'Mabel Matiz',
       'Dj LK da Esc√Ø¬ø¬Ω√Ø¬ø¬Ωcia', 'Gwen Stefani', 'Chuck Berry',
       'John Legend', 'Maldy', 'Gayle', 'Lauren Spencer Smith', 'Cherish',
       'Adassa', 'Farruko', 'Jaymes Young', 'Ckay', 'Jessica Darrow',
       'M√Ø¬ø¬Ω√Ø¬ø¬Ωne', 'Aitana', 'Julieta Venegas', 'Lisa',
       'Juan Cruz Toledo', 'BoyWithUke', 'Xam√Ø¬ø¬Ω√Ø¬ø¬Ω', 'Lit Killah',
       'Emmy Meli', 'Justin Quiles', 'Shawn Mendes', 'Aventura',
       'THE ANXIETY', 'Stromae', 'NEIKED', 'Oliver Tree', 'Young Thug',
       'Jnr Choi', 'Trueno', 'Sech', 'Olga Merediz', 'Surf Curse',
       'Jason Derulo', '21 Savage', '24kgoldn', 'Stephanie Beatriz',
       'Kanye West', 'Playboi Carti', 'Maluma', 'Prezioso', 'Ti√Ø¬ø¬Ω√Ø¬ø',
       'Mar√Ø¬ø¬Ω√Ø¬ø¬Ωlia Mendon√Ø¬ø¬Ω√Ø¬ø¬Ωa', 'TWICE', 'Giveon', 'Charli XCX',
       'SALES', 'Sleepy hallow', 'Masked Wolf', 'Anuel Aa', 'NIKI',
       'Tate McRae', 'Avicii', 'Tones and I', 'Juice WRLD', 'Nirvana',
       'Duncan Laurence', 'SiM', 'The Killers', 'Riton', 'Polo G',
       'Katy Perry', 'Dr. Dre', 'Dove Cameron', 'Mahmood', '50 Cent',
       'Yung Lean', 'The Rare Occasions', 'Intense', 'Luude',
       'Ryan Castro', 'GODZZ__-', 'Chase Atlantic', 'Mainstreet',
       'Alvaro Diaz', 'Z√Ø¬ø¬Ω√Ø¬ø¬Ω Fe', 'Muni Long', 'Vundabar', 'V',
       'Camila Cabello', 'Cris Mj', 'Anitta', 'Tulus', 'Zion & Lennox',
       'Residente', 'Eden Mu√Ø¬ø¬Ω√Ø', 'Treasure', 'Christian Nodal',
       'Kevin Gates', 'Tyga', 'Queen', 'YEAT', 'C. Tangana',
       'The Chainsmokers', 'NMIXX', 'Gotye', 'AnnenMayKantereit',
       'Paulo Londra', 'Danny Ocean', 'Lil Tjay', 'Willow', 'Demi Lovato',
       'Matu√Ø¬ø¬Ω√Ø¬ø¬Ω', 'De La Ghetto', 'Lil Baby', 'Ak4:20',
       'Lu√Ø¬ø¬Ω√Ø¬ø¬Ωsa Sonza', 'teto', 'Blackbear', 'Pharrell Williams',
       'Jordan Fisher', 'BIGBANG', 'Tony Dize', 'Buscabulla',
       'Polima WestCoast', 'Panic! At The Disco', 'PSY', 'Benson Boone',
       'KALUSH', 'Luciano', 'Shae Gill', 'MNEK', 'Ugly Dray', 'Jessi',
       'Chanel', 'Leah Kate', 'Sam Ryder', 'HA SUNG WOON',
       'The Goo Goo Dolls', 'Kevin Kaarl', 'Suki Waterhouse',
       'Musical Youth', 'BYOR', 'Paloma Faith', 'Childish Gambino',
       'Sidhu Moose Wala', 'Keisya Levronka', 'Victor Cibrian',
       'Metallica', 'Yung Gravy', 'Lasso', 'Nayeon', 'Sch√Ø¬ø¬Ω√Ø¬ø¬Ωrze',
       "Guns N' Roses", 'Burna Boy', 'L7nnon', 'Nessa Barrett',
       'LF System', 'Mc Vitin Da Igrejinha', 'Rels B', 'Snoop Dogg',
       'Luar La L', 'Ghost', 'Rex Orange County', 'Sofia Carson',
       'Luis R Conriquez', 'Melody', 'Elton John',
       'Interplanetary Criminal', 'Armani White', 'Oxlade', 'PnB Rock',
       'Ovy On The Drums', 'Lil Yachty', 'Fran C', 'Southstar',
       'girl in red', 'Rosa Walton', 'MC Ryan SP', 'Ludwig Goransson',
       'Jin', 'Selena Gomez'], dtype=object)

In [64]:
# Save the dataframe as a csv 
df.to_csv('spotify-2023-cleaned.csv', index=False)

# Song Features

### danceability
Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.

### energy
Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.

### key
The key the track is in. Integers map to pitches using standard Pitch Class notation. E.g. 0 = C, 1 = C#/Db, 2 = D, and so on.

### loudness
The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typical range between -60 and 0 db.

### mode
Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0.

### speechiness
Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.

### acousticness
A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic.

### instrumentalness
Predicts whether a track contains no vocals. "Ooh" and "aah" sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly "vocal". The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0.

### liveness
Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.

### valence
A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).

### tempo
The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.

-- from https://search.r-project.org/CRAN/refmans/billboard/html/spotify_track_data.html

In [65]:
df1 = pd.read_csv("C:\\Users\\nyolc\\OneDrive\\Asztali g√©p\\CS251\\spotify-2023.csv", encoding = "ISO-8859-1")
df1.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,263,45,10,826,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,126,58,14,382,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,207,91,14,949,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,207,125,12,548,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,133,87,15,425,144,A,Minor,65,23,80,14,63,11,6

In [66]:
# create a function that cleans the data
def clean_data(df1):
    # drop columns
    df1 = df1.drop(columns=['in_apple_playlists', 'in_apple_charts', 'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts'])
    
    # fill nulls
    df1 = df1.fillna('Unknown')
    
    # remove the row with the string value
    df1 = df1.drop(574)
    
    # convert to numeric
    df1.streams = pd.to_numeric(df1.streams)
    from datetime import date
    # combine date columns
    df1['released_date'] = df1.apply(lambda x: date(int(x['released_year']), int(x['released_month']), int(x['released_day'])), axis=1)
    # create season column
    df1['season'] = df1['released_month'].apply(lambda x: 'Winter' if x in [12, 1, 2] else 'Spring' if x in [3, 4, 5] else 'Summer' if x in [6, 7, 8] else 'Fall')
    #create day of the week column
    df1['day_of_week'] = df1['released_date'].apply(lambda x: x.strftime('%A'))

    
    # split artists as main and supporting artists
    df1['main_artist'] = df1['artist(s)_name'].str.split(',').str[0]
    df1['supporting_artists'] = df1['artist(s)_name'].str.split(',').str[1]
    
    # drop 'artist(s)_name'
    df1 = df1.drop(columns=['artist(s)_name'])
    
    return df1
#show the first 5 rows of the cleaned data
clean_data(df1).head()

,track_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,released_date,season,day_of_week,main_artist,supporting_artists
0,Seven (feat. Latto) (Explicit Ver.),2,2023,7,14,553,147,141381703,125,B,Major,80,89,83,31,0,8,4,2023-07-14,Summer,Friday,Latto,Jung Kook
1,LALA,1,2023,3,23,1474,48,133716286,92,C#,Major,71,61,74,7,0,10,4,2023-03-23,Spring,Thursday,Myke Towers,NaN
2,vampire,1,2023,6,30,1397,113,140003974,138,F,Major,51,32,53,17,0,31,6,2023-06-30,Summer,Friday,Olivia Rodrigo,NaN
3,Cruel Summer,1,2019,8,23,7858,100,800840817,170,A,Major,55,58,72,11,0,11,15,2019-08-23,Summer,Friday,Taylor Swift,NaN
4,WHERE SHE GOES,1,2023,5,18,3133,50,303236322,144,A,Minor,65,23,80,14,63,11,6,2023-05-18,Spring,Thursday,Bad Bunny,NaN

In [67]:
#reorder the columns
df1 = clean_data(df1)
df1 = df1[['track_name', 'main_artist', 'supporting_artists', 'artist_count', 'released_year', 'released_month', 'released_day', 'released_date', 'season', 'day_of_week', 'in_spotify_playlists', 'in_spotify_charts', 'streams', 'bpm', 'key', 'mode', 'danceability_%', 'valence_%', 'energy_%', 'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%']]
df1.head()

,track_name,main_artist,supporting_artists,artist_count,released_year,released_month,released_day,released_date,season,day_of_week,in_spotify_playlists,in_spotify_charts,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),Latto,Jung Kook,2,2023,7,14,2023-07-14,Summer,Friday,553,147,141381703,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,NaN,1,2023,3,23,2023-03-23,Spring,Thursday,1474,48,133716286,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,NaN,1,2023,6,30,2023-06-30,Summer,Friday,1397,113,140003974,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,NaN,1,2019,8,23,2019-08-23,Summer,Friday,7858,100,800840817,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,NaN,1,2023,5,18,2023-05-18,Spring,Thursday,3133,50,303236322,144,A,Minor,65,23,80,14,63,11,6

In [68]:
#select random sample of 5 rows
df1.sample(5)
#show the streams of these samples
df1.sample(5)['streams']

582      60680939
316     367814306
292    1449799467
884     273914335
750    1023187129
Name: streams, dtype: int64

In [69]:
df1.shape

(952, 23)